# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/x-language

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/x-language

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/x-language/CMakeFiles /workspaces/x-language//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/x-language/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named always

# Build rule for target.
always: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 always
.PHONY : always

# fast build rule for target.
always/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/always.dir/build.make CMakeFiles/always.dir/build
.PHONY : always/fast

#=============================================================================
# Target rules for targets named build_go_obj

# Build rule for target.
build_go_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_go_obj
.PHONY : build_go_obj

# fast build rule for target.
build_go_obj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_go_obj.dir/build.make CMakeFiles/build_go_obj.dir/build
.PHONY : build_go_obj/fast

#=============================================================================
# Target rules for targets named scheduler

# Build rule for target.
scheduler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scheduler
.PHONY : scheduler

# fast build rule for target.
scheduler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/build
.PHONY : scheduler/fast

gc/src/alloc.o: gc/src/alloc.c.o
.PHONY : gc/src/alloc.o

# target to build an object file
gc/src/alloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/gc/src/alloc.c.o
.PHONY : gc/src/alloc.c.o

gc/src/alloc.i: gc/src/alloc.c.i
.PHONY : gc/src/alloc.i

# target to preprocess a source file
gc/src/alloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/gc/src/alloc.c.i
.PHONY : gc/src/alloc.c.i

gc/src/alloc.s: gc/src/alloc.c.s
.PHONY : gc/src/alloc.s

# target to generate assembly for a file
gc/src/alloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/gc/src/alloc.c.s
.PHONY : gc/src/alloc.c.s

gc/src/gc.o: gc/src/gc.c.o
.PHONY : gc/src/gc.o

# target to build an object file
gc/src/gc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/gc/src/gc.c.o
.PHONY : gc/src/gc.c.o

gc/src/gc.i: gc/src/gc.c.i
.PHONY : gc/src/gc.i

# target to preprocess a source file
gc/src/gc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/gc/src/gc.c.i
.PHONY : gc/src/gc.c.i

gc/src/gc.s: gc/src/gc.c.s
.PHONY : gc/src/gc.s

# target to generate assembly for a file
gc/src/gc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/gc/src/gc.c.s
.PHONY : gc/src/gc.c.s

runtime/src/array.o: runtime/src/array.c.o
.PHONY : runtime/src/array.o

# target to build an object file
runtime/src/array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/array.c.o
.PHONY : runtime/src/array.c.o

runtime/src/array.i: runtime/src/array.c.i
.PHONY : runtime/src/array.i

# target to preprocess a source file
runtime/src/array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/array.c.i
.PHONY : runtime/src/array.c.i

runtime/src/array.s: runtime/src/array.c.s
.PHONY : runtime/src/array.s

# target to generate assembly for a file
runtime/src/array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/array.c.s
.PHONY : runtime/src/array.c.s

runtime/src/atomic.o: runtime/src/atomic.c.o
.PHONY : runtime/src/atomic.o

# target to build an object file
runtime/src/atomic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/atomic.c.o
.PHONY : runtime/src/atomic.c.o

runtime/src/atomic.i: runtime/src/atomic.c.i
.PHONY : runtime/src/atomic.i

# target to preprocess a source file
runtime/src/atomic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/atomic.c.i
.PHONY : runtime/src/atomic.c.i

runtime/src/atomic.s: runtime/src/atomic.c.s
.PHONY : runtime/src/atomic.s

# target to generate assembly for a file
runtime/src/atomic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/atomic.c.s
.PHONY : runtime/src/atomic.c.s

runtime/src/crypto.o: runtime/src/crypto.c.o
.PHONY : runtime/src/crypto.o

# target to build an object file
runtime/src/crypto.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/crypto.c.o
.PHONY : runtime/src/crypto.c.o

runtime/src/crypto.i: runtime/src/crypto.c.i
.PHONY : runtime/src/crypto.i

# target to preprocess a source file
runtime/src/crypto.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/crypto.c.i
.PHONY : runtime/src/crypto.c.i

runtime/src/crypto.s: runtime/src/crypto.c.s
.PHONY : runtime/src/crypto.s

# target to generate assembly for a file
runtime/src/crypto.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/crypto.c.s
.PHONY : runtime/src/crypto.c.s

runtime/src/error.o: runtime/src/error.c.o
.PHONY : runtime/src/error.o

# target to build an object file
runtime/src/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/error.c.o
.PHONY : runtime/src/error.c.o

runtime/src/error.i: runtime/src/error.c.i
.PHONY : runtime/src/error.i

# target to preprocess a source file
runtime/src/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/error.c.i
.PHONY : runtime/src/error.c.i

runtime/src/error.s: runtime/src/error.c.s
.PHONY : runtime/src/error.s

# target to generate assembly for a file
runtime/src/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/error.c.s
.PHONY : runtime/src/error.c.s

runtime/src/ggc.o: runtime/src/ggc.c.o
.PHONY : runtime/src/ggc.o

# target to build an object file
runtime/src/ggc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/ggc.c.o
.PHONY : runtime/src/ggc.c.o

runtime/src/ggc.i: runtime/src/ggc.c.i
.PHONY : runtime/src/ggc.i

# target to preprocess a source file
runtime/src/ggc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/ggc.c.i
.PHONY : runtime/src/ggc.c.i

runtime/src/ggc.s: runtime/src/ggc.c.s
.PHONY : runtime/src/ggc.s

# target to generate assembly for a file
runtime/src/ggc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/ggc.c.s
.PHONY : runtime/src/ggc.c.s

runtime/src/io.o: runtime/src/io.c.o
.PHONY : runtime/src/io.o

# target to build an object file
runtime/src/io.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/io.c.o
.PHONY : runtime/src/io.c.o

runtime/src/io.i: runtime/src/io.c.i
.PHONY : runtime/src/io.i

# target to preprocess a source file
runtime/src/io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/io.c.i
.PHONY : runtime/src/io.c.i

runtime/src/io.s: runtime/src/io.c.s
.PHONY : runtime/src/io.s

# target to generate assembly for a file
runtime/src/io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/io.c.s
.PHONY : runtime/src/io.c.s

runtime/src/main.o: runtime/src/main.c.o
.PHONY : runtime/src/main.o

# target to build an object file
runtime/src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/main.c.o
.PHONY : runtime/src/main.c.o

runtime/src/main.i: runtime/src/main.c.i
.PHONY : runtime/src/main.i

# target to preprocess a source file
runtime/src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/main.c.i
.PHONY : runtime/src/main.c.i

runtime/src/main.s: runtime/src/main.c.s
.PHONY : runtime/src/main.s

# target to generate assembly for a file
runtime/src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/main.c.s
.PHONY : runtime/src/main.c.s

runtime/src/queue.o: runtime/src/queue.c.o
.PHONY : runtime/src/queue.o

# target to build an object file
runtime/src/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/queue.c.o
.PHONY : runtime/src/queue.c.o

runtime/src/queue.i: runtime/src/queue.c.i
.PHONY : runtime/src/queue.i

# target to preprocess a source file
runtime/src/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/queue.c.i
.PHONY : runtime/src/queue.c.i

runtime/src/queue.s: runtime/src/queue.c.s
.PHONY : runtime/src/queue.s

# target to generate assembly for a file
runtime/src/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/queue.c.s
.PHONY : runtime/src/queue.c.s

runtime/src/scheduler.o: runtime/src/scheduler.c.o
.PHONY : runtime/src/scheduler.o

# target to build an object file
runtime/src/scheduler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/scheduler.c.o
.PHONY : runtime/src/scheduler.c.o

runtime/src/scheduler.i: runtime/src/scheduler.c.i
.PHONY : runtime/src/scheduler.i

# target to preprocess a source file
runtime/src/scheduler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/scheduler.c.i
.PHONY : runtime/src/scheduler.c.i

runtime/src/scheduler.s: runtime/src/scheduler.c.s
.PHONY : runtime/src/scheduler.s

# target to generate assembly for a file
runtime/src/scheduler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/scheduler.c.s
.PHONY : runtime/src/scheduler.c.s

runtime/src/strings.o: runtime/src/strings.c.o
.PHONY : runtime/src/strings.o

# target to build an object file
runtime/src/strings.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/strings.c.o
.PHONY : runtime/src/strings.c.o

runtime/src/strings.i: runtime/src/strings.c.i
.PHONY : runtime/src/strings.i

# target to preprocess a source file
runtime/src/strings.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/strings.c.i
.PHONY : runtime/src/strings.c.i

runtime/src/strings.s: runtime/src/strings.c.s
.PHONY : runtime/src/strings.s

# target to generate assembly for a file
runtime/src/strings.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/src/strings.c.s
.PHONY : runtime/src/strings.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... always"
	@echo "... build_go_obj"
	@echo "... scheduler"
	@echo "... gc/src/alloc.o"
	@echo "... gc/src/alloc.i"
	@echo "... gc/src/alloc.s"
	@echo "... gc/src/gc.o"
	@echo "... gc/src/gc.i"
	@echo "... gc/src/gc.s"
	@echo "... runtime/src/array.o"
	@echo "... runtime/src/array.i"
	@echo "... runtime/src/array.s"
	@echo "... runtime/src/atomic.o"
	@echo "... runtime/src/atomic.i"
	@echo "... runtime/src/atomic.s"
	@echo "... runtime/src/crypto.o"
	@echo "... runtime/src/crypto.i"
	@echo "... runtime/src/crypto.s"
	@echo "... runtime/src/error.o"
	@echo "... runtime/src/error.i"
	@echo "... runtime/src/error.s"
	@echo "... runtime/src/ggc.o"
	@echo "... runtime/src/ggc.i"
	@echo "... runtime/src/ggc.s"
	@echo "... runtime/src/io.o"
	@echo "... runtime/src/io.i"
	@echo "... runtime/src/io.s"
	@echo "... runtime/src/main.o"
	@echo "... runtime/src/main.i"
	@echo "... runtime/src/main.s"
	@echo "... runtime/src/queue.o"
	@echo "... runtime/src/queue.i"
	@echo "... runtime/src/queue.s"
	@echo "... runtime/src/scheduler.o"
	@echo "... runtime/src/scheduler.i"
	@echo "... runtime/src/scheduler.s"
	@echo "... runtime/src/strings.o"
	@echo "... runtime/src/strings.i"
	@echo "... runtime/src/strings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

