# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/x-language

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/x-language

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/x-language/CMakeFiles /workspaces/x-language//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/x-language/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named scheduler

# Build rule for target.
scheduler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scheduler
.PHONY : scheduler

# fast build rule for target.
scheduler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/build
.PHONY : scheduler/fast

runtime/array.o: runtime/array.c.o
.PHONY : runtime/array.o

# target to build an object file
runtime/array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/array.c.o
.PHONY : runtime/array.c.o

runtime/array.i: runtime/array.c.i
.PHONY : runtime/array.i

# target to preprocess a source file
runtime/array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/array.c.i
.PHONY : runtime/array.c.i

runtime/array.s: runtime/array.c.s
.PHONY : runtime/array.s

# target to generate assembly for a file
runtime/array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/array.c.s
.PHONY : runtime/array.c.s

runtime/error.o: runtime/error.c.o
.PHONY : runtime/error.o

# target to build an object file
runtime/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/error.c.o
.PHONY : runtime/error.c.o

runtime/error.i: runtime/error.c.i
.PHONY : runtime/error.i

# target to preprocess a source file
runtime/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/error.c.i
.PHONY : runtime/error.c.i

runtime/error.s: runtime/error.c.s
.PHONY : runtime/error.s

# target to generate assembly for a file
runtime/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/error.c.s
.PHONY : runtime/error.c.s

runtime/ggc.o: runtime/ggc.c.o
.PHONY : runtime/ggc.o

# target to build an object file
runtime/ggc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/ggc.c.o
.PHONY : runtime/ggc.c.o

runtime/ggc.i: runtime/ggc.c.i
.PHONY : runtime/ggc.i

# target to preprocess a source file
runtime/ggc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/ggc.c.i
.PHONY : runtime/ggc.c.i

runtime/ggc.s: runtime/ggc.c.s
.PHONY : runtime/ggc.s

# target to generate assembly for a file
runtime/ggc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/ggc.c.s
.PHONY : runtime/ggc.c.s

runtime/io.o: runtime/io.c.o
.PHONY : runtime/io.o

# target to build an object file
runtime/io.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/io.c.o
.PHONY : runtime/io.c.o

runtime/io.i: runtime/io.c.i
.PHONY : runtime/io.i

# target to preprocess a source file
runtime/io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/io.c.i
.PHONY : runtime/io.c.i

runtime/io.s: runtime/io.c.s
.PHONY : runtime/io.s

# target to generate assembly for a file
runtime/io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/io.c.s
.PHONY : runtime/io.c.s

runtime/main.o: runtime/main.c.o
.PHONY : runtime/main.o

# target to build an object file
runtime/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/main.c.o
.PHONY : runtime/main.c.o

runtime/main.i: runtime/main.c.i
.PHONY : runtime/main.i

# target to preprocess a source file
runtime/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/main.c.i
.PHONY : runtime/main.c.i

runtime/main.s: runtime/main.c.s
.PHONY : runtime/main.s

# target to generate assembly for a file
runtime/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/main.c.s
.PHONY : runtime/main.c.s

runtime/queue.o: runtime/queue.c.o
.PHONY : runtime/queue.o

# target to build an object file
runtime/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/queue.c.o
.PHONY : runtime/queue.c.o

runtime/queue.i: runtime/queue.c.i
.PHONY : runtime/queue.i

# target to preprocess a source file
runtime/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/queue.c.i
.PHONY : runtime/queue.c.i

runtime/queue.s: runtime/queue.c.s
.PHONY : runtime/queue.s

# target to generate assembly for a file
runtime/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/queue.c.s
.PHONY : runtime/queue.c.s

runtime/scheduler.o: runtime/scheduler.c.o
.PHONY : runtime/scheduler.o

# target to build an object file
runtime/scheduler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/scheduler.c.o
.PHONY : runtime/scheduler.c.o

runtime/scheduler.i: runtime/scheduler.c.i
.PHONY : runtime/scheduler.i

# target to preprocess a source file
runtime/scheduler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/scheduler.c.i
.PHONY : runtime/scheduler.c.i

runtime/scheduler.s: runtime/scheduler.c.s
.PHONY : runtime/scheduler.s

# target to generate assembly for a file
runtime/scheduler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scheduler.dir/build.make CMakeFiles/scheduler.dir/runtime/scheduler.c.s
.PHONY : runtime/scheduler.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... scheduler"
	@echo "... runtime/array.o"
	@echo "... runtime/array.i"
	@echo "... runtime/array.s"
	@echo "... runtime/error.o"
	@echo "... runtime/error.i"
	@echo "... runtime/error.s"
	@echo "... runtime/ggc.o"
	@echo "... runtime/ggc.i"
	@echo "... runtime/ggc.s"
	@echo "... runtime/io.o"
	@echo "... runtime/io.i"
	@echo "... runtime/io.s"
	@echo "... runtime/main.o"
	@echo "... runtime/main.i"
	@echo "... runtime/main.s"
	@echo "... runtime/queue.o"
	@echo "... runtime/queue.i"
	@echo "... runtime/queue.s"
	@echo "... runtime/scheduler.o"
	@echo "... runtime/scheduler.i"
	@echo "... runtime/scheduler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

